apiVersion: v1
kind: ConfigMap
metadata:
  name: tomcat-jsp-config
  namespace: default
data:
  index.jsp: |
    <%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
    <%@ page import="java.sql.*"%>
    <h1>DB</h2>
    <%
            Connection conn=null;
            try{
                    String Url="jdbc:mysql://database-1.cf244k80ewqw.ap-northeast-2.rds.amazonaws.com:3306/testdb";
                    String Id="admin";
                    String Pass="test1234";

                    Class.forName("com.mysql.jdbc.Driver");
                    conn=DriverManager.getConnection(Url,Id,Pass);
                    out.println("was-db Connection Success!");
            }catch(Exception e) {
                    e.printStackTrace();
    }
    %>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: iiilee0907/tomcat:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: jsp-volume
          mountPath: /usr/local/tomcat/webapps/ROOT/exam/index.jsp
          subPath: index.jsp
      volumes:
      - name: jsp-volume
        configMap:
          name: tomcat-jsp-config    

