apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "tom-ingress"
  labels:
    app.kubernetes.io/name: "tom-ingress"
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: tomcat-group
spec:
  ingressClassName: alb
  rules:
    - host: www.rainhyeon.store
      http:
        paths:
          - pathType: Prefix
            path: /exam
            backend:
              service:
                name: tom-service
                port:
                  number: 80
